### ISSUE TITLE
warning: keyword 'where' does not need to be escaped in argument list

### ISSUE THREAD

**Issue by mackoj** [yonaskolb/SwagGen#125]
Hi I have a few of these should I submit a PR to fix this warning ?

**Comment by yonaskolb** [comment]
Yes, you're welcome to submit a PR for this. It's tricky because `where` needs to be escaped in some cases, just not argument lists. The same goes for lots of other names that are listed in `SwiftFormatter` This could perhaps be fixed by escaping params in the actual template via a Stencil filter but that's more maintenance, or do you have another solution?
