### ISSUE TITLE
You don’t have permission to save the file “security” in the folder “org.swift.swiftpm”

### ISSUE THREAD

**Issue by smolskyaleksey** [yonaskolb/SwagGen#304]
<img width="1732" alt="Снимок экрана 2022-04-15 в 11 36 56" src="https://user-images.githubusercontent.com/6605765/163547547-8760b2bf-f1ed-4250-9765-766068a1d13a.png">

Hi I run ```brew install SwagGen``` and get error 

``` warning: Failed creating default security location, Error Domain=NSCocoaErrorDomain Code=513 "You don’t have permission to save the file “security” in the folder “org.swift.swiftpm”." UserInfo={NSFilePath=/Users/aleksey.smolskiy/Library/org.swift.swiftpm/security, NSUnderlyingError=0x60000111a6a0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}} ```

How can I fixed it?

**Comment by JanC** [comment]
hey,
this looks more like an issue with homebrew itself and not realted to SwagGen.

Do other brew install commands work?

**Comment by smolskyaleksey** [comment]
Hi, what kind of command do you want check
- search
- update
works

**Comment by cwagdev** [comment]
I had to verify `xcode-select` was set to an appropriate Xcode installation, when it was set to `/Library/Developer/CommandLineTools` I was getting this message.

By running `sudo xcode-select -s /Applications/Xcode.app/Contents/Developer` and then trying again the issue was resolved.

I was actually seeing this issue with [another package](https://github.com/RobotsAndPencils/xcodes) but came across this issue from Google

**Comment by yonaskolb** [comment]
Cool, closing this issue as not related to SwagGen
