### ISSUE TITLE
Cococapods podspec

### ISSUE THREAD

**Issue by danielbotka** [yonaskolb/SwagGen#59]
Hi,

I found an other issue with the podspec, there's a dependency to an other library:
`s.dependency 'JSONUtilities', '~> 3.3.8'`
The error is: `None of your spec sources contain a spec satisfying the dependency: 'JSONUtilities (~> 3.3.8)'.`

I tried 3.2.0 and also without locking the version, so it would use 5.0.0 but both of them are breaking the generated code. This is the associated library: https://cocoapods.org/?q=jsonutilities

It seems they never had a version 3.3.8 :/

**Comment by yonaskolb** [comment]
Oh bugger.
It's because the dependency is actually using `yonaskolb/JSONUtilities` but a podspec can't specify a different fork for a dependency. The fork is needed to fix some issues with certain specs. For example if the spec contains:
- arrays of arrays
- dictionaries of dictionaries
- property names with `.` in them

If you don't have those problems, you could upgrade to the normal `5.0.0`, and just fix the compiler errors in the template (I'm guessing the way keyPath is passed when not a string literal is an issue)

https://github.com/yonaskolb/SwagGen/issues/32 will fix this issue entirely by replacing JSONUtilities with Swift's Codable, but that still needs some work
